# Generated by Django 5.1.1 on 2024-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("programme", models.CharField(max_length=100)),
                ("semester", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
            ],
        ),
    ]
