# Generated by Django 5.1.1 on 2024-09-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="usn",
            field=models.CharField(default="DEFAULT_USN", max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="programme",
            field=models.CharField(
                choices=[("BCA", "BCA")], default="BCA", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="section",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="semester",
            field=models.IntegerField(
                choices=[
                    (1, "1st Semester"),
                    (2, "2nd Semester"),
                    (3, "3rd Semester"),
                    (4, "4th Semester"),
                    (5, "5th Semester"),
                    (6, "6th Semester"),
                ]
            ),
        ),
    ]
