# Generated by Django 5.1.1 on 2025-04-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_usn_alter_student_programme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
